version: "3.4"

services:
  webserver:
    image: nginx:1.25.3
    container_name: quiz_frontend
    restart: unless-stopped
    tty: true
    ports:
      - '80:80'
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
  